export const baseStyles = [
  "    :root {",
  "      --bg: #f3f0ea;",
  "      --panel: #ffffff;",
  "      --ink: #1f1d1a;",
  "      --muted: #6f6a62;",
  "      --line: #ddd6cb;",
  "      --soft: #f8f6f2;",
  "      --accent: #0f766e;",
  "      --accent-soft: #daf2ef;",
  "      --danger: #ad3b2f;",
  "      --danger-soft: #fbe9e6;",
  "      --radius: 14px;",
  "    }",
  "",
  "    * { box-sizing: border-box; }",
  "",
  "    html, body { height: 100%; }",
  "",
  "    body {",
  "      margin: 0;",
  "      font-family: \"Manrope\", \"Segoe UI\", sans-serif;",
  "      color: var(--ink);",
  "      background: radial-gradient(circle at 20% 0%, #f8f5ef 0%, var(--bg) 50%, #efebe4 100%);",
  "      -webkit-text-size-adjust: 100%;",
  "    }",
  "",
  "    .hidden { display: none !important; }",
  "",
  "    .landing {",
  "      min-height: 100vh;",
  "      min-height: 100dvh;",
  "      display: grid;",
  "      place-items: center;",
  "      padding: 24px;",
  "    }",
  "",
  "    .landing-card {",
  "      width: min(860px, 100%);",
  "      border: 1px solid var(--line);",
  "      border-radius: 22px;",
  "      padding: clamp(24px, 4vw, 42px);",
  "      background: rgba(255, 255, 255, 0.92);",
  "      box-shadow: 0 26px 60px rgba(20, 18, 13, 0.08);",
  "      backdrop-filter: blur(4px);",
  "    }",
  "",
  "    .landing-eyebrow {",
  "      margin: 0 0 6px;",
  "      text-transform: uppercase;",
  "      letter-spacing: 0.1em;",
  "      font-size: 11px;",
  "      font-weight: 700;",
  "      color: var(--muted);",
  "    }",
  "",
  "    .landing h1 {",
  "      margin: 0;",
  "      font-family: \"Newsreader\", Georgia, serif;",
  "      font-size: clamp(34px, 5vw, 54px);",
  "      line-height: 1.02;",
  "      font-weight: 700;",
  "      letter-spacing: -0.02em;",
  "    }",
  "",
  "    .landing p {",
  "      margin: 14px 0 0;",
  "      color: var(--muted);",
  "      max-width: 66ch;",
  "      line-height: 1.6;",
  "    }",
  "",
  "    .landing ul {",
  "      margin: 18px 0 0;",
  "      padding-left: 20px;",
  "      color: var(--ink);",
  "      display: grid;",
  "      gap: 7px;",
  "      line-height: 1.45;",
  "    }",
  "",
  "    .button,",
  "    button,",
  "    input,",
  "    textarea,",
  "    select {",
  "      font: inherit;",
  "    }",
  "",
  "    .button {",
  "      appearance: none;",
  "      border: 1px solid var(--line);",
  "      border-radius: 12px;",
  "      background: #fff;",
  "      color: var(--ink);",
  "      padding: 10px 14px;",
  "      font-weight: 600;",
  "      cursor: pointer;",
  "      text-decoration: none;",
  "      display: inline-flex;",
  "      align-items: center;",
  "      justify-content: center;",
  "      gap: 8px;",
  "      transition: transform 120ms ease, box-shadow 120ms ease, background 120ms ease;",
  "    }",
  "",
  "    .button:hover {",
  "      transform: translateY(-1px);",
  "      box-shadow: 0 6px 14px rgba(15, 12, 8, 0.08);",
  "    }",
  "",
  "    .button:disabled {",
  "      cursor: not-allowed;",
  "      opacity: 0.6;",
  "      transform: none;",
  "      box-shadow: none;",
  "    }",
  "",
  "    .button.primary {",
  "      background: var(--ink);",
  "      color: #fff;",
  "      border-color: var(--ink);",
  "    }",
  "",
  "    .button.accent {",
  "      background: var(--accent);",
  "      color: #fff;",
  "      border-color: var(--accent);",
  "    }",
  "",
  "    .button.soft {",
  "      background: var(--soft);",
  "    }",
  "",
  "    .button.danger {",
  "      border-color: #d9b3ad;",
  "      background: var(--danger-soft);",
  "      color: var(--danger);",
  "    }",
  "",
  "    .landing-actions {",
  "      margin-top: 24px;",
  "      display: flex;",
  "      gap: 12px;",
  "      flex-wrap: wrap;",
  "    }",
  "",
  "    .app-shell {",
  "      height: 100vh;",
  "      height: 100dvh;",
  "      display: grid;",
  "      grid-template-columns: 330px 1fr;",
  "      gap: 14px;",
  "      padding: 14px;",
  "    }",
  "",
  "    .sidebar,",
  "    .main {",
  "      background: rgba(255, 255, 255, 0.9);",
  "      border: 1px solid var(--line);",
  "      border-radius: 18px;",
  "      min-width: 0;",
  "    }",
  "",
  "    .sidebar {",
  "      display: grid;",
  "      grid-template-rows: auto minmax(0, 1fr) auto;",
  "      overflow: hidden;",
  "    }",
  "",
  "    .sidebar-head,",
  "    .sidebar-foot {",
  "      padding: 14px;",
  "      border-bottom: 1px solid var(--line);",
  "      background: rgba(255, 255, 255, 0.78);",
  "    }",
  "",
  "    .sidebar-foot {",
  "      border-top: 1px solid var(--line);",
  "      border-bottom: none;",
  "      display: grid;",
  "      gap: 8px;",
  "      font-size: 12px;",
  "      color: var(--muted);",
  "    }",
  "",
  "    .brand {",
  "      font-family: \"Newsreader\", Georgia, serif;",
  "      font-weight: 700;",
  "      font-size: 24px;",
  "      line-height: 1;",
  "      margin-bottom: 10px;",
  "    }",
  "",
  "    .sidebar-actions {",
  "      display: grid;",
  "      gap: 8px;",
  "    }",
  "",
  "    .project-tree {",
  "      overflow-y: auto;",
  "      padding: 12px;",
  "      display: grid;",
  "      gap: 10px;",
  "      align-content: start;",
  "    }",
  "",
  "    .project-node {",
  "      border: 1px solid var(--line);",
  "      border-radius: 12px;",
  "      overflow: hidden;",
  "      background: #fff;",
  "    }"
].join("\n");
