export const baseStyles = [
  "    :root {",
  "      --bg: #f6f6f6;",
  "      --panel: #ffffff;",
  "      --ink: #101010;",
  "      --muted: #5f5f5f;",
  "      --line: #d8d8d8;",
  "      --soft: #f2f2f2;",
  "      --accent: #101010;",
  "      --accent-soft: #efefef;",
  "      --danger: #101010;",
  "      --danger-soft: #f2f2f2;",
  "      --radius-sm: 12px;",
  "      --radius: 14px;",
  "      --radius-lg: 18px;",
  "      --radius-xl: 22px;",
  "      --shadow-xs: 0 1px 2px rgba(0, 0, 0, 0.05);",
  "      --shadow-sm: 0 5px 14px rgba(0, 0, 0, 0.04);",
  "      --shadow-md: 0 14px 32px rgba(0, 0, 0, 0.05);",
  "    }",
  "",
  "    * { box-sizing: border-box; }",
  "",
  "    html, body { height: 100%; }",
  "",
  "    body {",
  "      margin: 0;",
  "      font-family: \"Manrope\", \"Segoe UI\", sans-serif;",
  "      color: var(--ink);",
  "      background: var(--bg);",
  "      -webkit-text-size-adjust: 100%;",
  "    }",
  "",
  "    .hidden { display: none !important; }",
  "",
  "    .landing {",
  "      min-height: 100vh;",
  "      min-height: 100dvh;",
  "      display: grid;",
  "      place-items: center;",
  "      padding: 24px;",
  "    }",
  "",
  "    .landing-card {",
  "      width: min(860px, 100%);",
  "      border: 1px solid var(--line);",
  "      border-radius: var(--radius-xl);",
  "      padding: clamp(24px, 4vw, 42px);",
  "      background: var(--panel);",
  "      box-shadow: var(--shadow-md);",
  "    }",
  "",
  "    .landing-eyebrow {",
  "      margin: 0 0 6px;",
  "      text-transform: uppercase;",
  "      letter-spacing: 0.1em;",
  "      font-size: 11px;",
  "      font-weight: 700;",
  "      color: var(--muted);",
  "    }",
  "",
  "    .landing h1 {",
  "      margin: 0;",
  "      font-family: \"Newsreader\", Georgia, serif;",
  "      font-size: clamp(34px, 5vw, 54px);",
  "      line-height: 1.02;",
  "      font-weight: 700;",
  "      letter-spacing: -0.02em;",
  "    }",
  "",
  "    .landing p {",
  "      margin: 14px 0 0;",
  "      color: var(--muted);",
  "      max-width: 66ch;",
  "      line-height: 1.6;",
  "    }",
  "",
  "    .landing ul {",
  "      margin: 18px 0 0;",
  "      padding-left: 20px;",
  "      color: var(--ink);",
  "      display: grid;",
  "      gap: 7px;",
  "      line-height: 1.45;",
  "    }",
  "",
  "    .button,",
  "    button,",
  "    input,",
  "    textarea,",
  "    select {",
  "      font: inherit;",
  "    }",
  "",
  "    .button {",
  "      appearance: none;",
  "      border: 1px solid var(--line);",
  "      border-radius: var(--radius-sm);",
  "      background: var(--panel);",
  "      color: var(--ink);",
  "      padding: 10px 14px;",
  "      font-weight: 600;",
  "      cursor: pointer;",
  "      text-decoration: none;",
  "      display: inline-flex;",
  "      align-items: center;",
  "      justify-content: center;",
  "      gap: 8px;",
  "      transition: transform 120ms ease, box-shadow 120ms ease, background 120ms ease, border-color 120ms ease;",
  "      box-shadow: var(--shadow-xs);",
  "    }",
  "",
  "    .button:hover {",
  "      transform: translateY(-1px);",
  "      box-shadow: var(--shadow-sm);",
  "    }",
  "",
  "    .button:disabled {",
  "      cursor: not-allowed;",
  "      opacity: 0.6;",
  "      transform: none;",
  "      box-shadow: none;",
  "    }",
  "",
  "    .button.primary {",
  "      background: var(--ink);",
  "      color: #fff;",
  "      border-color: var(--ink);",
  "    }",
  "",
  "    .button.accent {",
  "      background: var(--ink);",
  "      color: #fff;",
  "      border-color: var(--ink);",
  "    }",
  "",
  "    .button.soft {",
  "      background: var(--soft);",
  "    }",
  "",
  "    .button.danger {",
  "      border-color: var(--ink);",
  "      background: var(--panel);",
  "      color: var(--ink);",
  "    }",

  "    .button:focus-visible,",
  "    input:focus-visible,",
  "    textarea:focus-visible,",
  "    select:focus-visible {",
  "      outline: 2px solid var(--ink);",
  "      outline-offset: 2px;",
  "    }",
  "",
  "    .landing-actions {",
  "      margin-top: 24px;",
  "      display: flex;",
  "      gap: 12px;",
  "      flex-wrap: wrap;",
  "    }",
  "",
  "    .app-shell {",
  "      height: 100vh;",
  "      height: 100dvh;",
  "      display: grid;",
  "      grid-template-columns: 330px 1fr;",
  "      gap: 14px;",
  "      padding: 14px;",
  "    }",
  "",
  "    .sidebar,",
  "    .main {",
  "      background: var(--panel);",
  "      border: 1px solid var(--line);",
  "      border-radius: var(--radius-lg);",
  "      box-shadow: var(--shadow-sm);",
  "      min-width: 0;",
  "    }",
  "",
  "    .sidebar {",
  "      display: grid;",
  "      grid-template-rows: auto minmax(0, 1fr) auto;",
  "      overflow: hidden;",
  "    }",
  "",
  "    .sidebar-head,",
  "    .sidebar-foot {",
  "      padding: 14px;",
  "      border-bottom: 1px solid var(--line);",
  "      background: var(--panel);",
  "    }",
  "",
  "    .sidebar-foot {",
  "      border-top: 1px solid var(--line);",
  "      border-bottom: none;",
  "      display: grid;",
  "      gap: 8px;",
  "      font-size: 12px;",
  "      color: var(--muted);",
  "    }",
  "",
  "    .brand {",
  "      font-family: \"Newsreader\", Georgia, serif;",
  "      font-weight: 700;",
  "      font-size: 24px;",
  "      line-height: 1;",
  "      margin-bottom: 10px;",
  "    }",
  "",
  "    .sidebar-actions {",
  "      display: grid;",
  "      gap: 8px;",
  "    }",
  "",
  "    .project-tree {",
  "      overflow-y: auto;",
  "      padding: 12px;",
  "      display: grid;",
  "      gap: 10px;",
  "      align-content: start;",
  "    }",
  "",
  "    .project-node {",
  "      border: 1px solid var(--line);",
  "      border-radius: var(--radius-sm);",
  "      overflow: hidden;",
  "      background: var(--panel);",
  "      box-shadow: var(--shadow-xs);",
  "    }"
].join("\n");
