export const componentStyles = [
  "    .field textarea {",
  "      min-height: 88px;",
  "      resize: vertical;",
  "      line-height: 1.45;",
  "    }",
  "",
  "    .actions-row {",
  "      display: flex;",
  "      gap: 8px;",
  "      flex-wrap: wrap;",
  "      align-items: center;",
  "    }",
  "",
  "    .stat {",
  "      border: 1px solid var(--line);",
  "      border-radius: var(--radius-sm);",
  "      background: var(--panel);",
  "      box-shadow: var(--shadow-xs);",
  "      padding: 12px;",
  "      display: grid;",
  "      gap: 5px;",
  "    }",
  "",
  "    .stat .label {",
  "      color: var(--muted);",
  "      font-size: 11px;",
  "      text-transform: uppercase;",
  "      letter-spacing: 0.06em;",
  "      font-weight: 700;",
  "    }",
  "",
  "    .stat .value {",
  "      font-size: 22px;",
  "      line-height: 1;",
  "      font-weight: 700;",
  "      color: var(--ink);",
  "    }",
  "",
  "    .chips {",
  "      display: flex;",
  "      flex-wrap: wrap;",
  "      gap: 7px;",
  "    }",
  "",
  "    .chip {",
  "      display: inline-flex;",
  "      border: 1px solid var(--line);",
  "      border-radius: 999px;",
  "      padding: 5px 10px;",
  "      font-size: 11px;",
  "      color: var(--muted);",
  "      background: var(--soft);",
  "    }",
  "",
  "    .explorer-controls {",
  "      display: grid;",
  "      gap: 10px;",
  "      grid-template-columns: 2fr 1fr 1fr auto;",
  "      align-items: end;",
  "    }",
  "",
  "    .paper-grid {",
  "      display: grid;",
  "      gap: 10px;",
  "    }",
  "",
  "    .paper-card {",
  "      border: 1px solid var(--line);",
  "      border-radius: var(--radius-sm);",
  "      padding: 12px;",
  "      background: var(--panel);",
  "      box-shadow: var(--shadow-xs);",
  "      display: grid;",
  "      gap: 9px;",
  "    }",
  "",
  "    .paper-card h4 {",
  "      margin: 0;",
  "      font-size: 16px;",
  "      line-height: 1.35;",
  "    }",
  "",
  "    .paper-meta {",
  "      margin: 0;",
  "      color: var(--muted);",
  "      font-size: 12px;",
  "      display: flex;",
  "      gap: 7px;",
  "      flex-wrap: wrap;",
  "      align-items: center;",
  "    }",
  "",
  "    .paper-abstract {",
  "      margin: 0;",
  "      color: var(--ink);",
  "      font-size: 14px;",
  "      line-height: 1.55;",
  "    }",
  "",
  "    .tier-badge {",
  "      border-radius: 999px;",
  "      padding: 4px 8px;",
  "      font-size: 10px;",
  "      font-weight: 700;",
  "      letter-spacing: 0.05em;",
  "      text-transform: uppercase;",
  "      border: 1px solid var(--line);",
  "      background: var(--panel);",
  "    }",
  "",
  "    .tier-FOUNDATIONAL { background: var(--ink); border-color: var(--ink); color: #fff; }",
  "    .tier-DEPTH { background: var(--soft); border-color: #cfcfcf; color: var(--ink); }",
  "    .tier-BACKGROUND { background: var(--panel); border-color: var(--ink); color: var(--ink); }",
  "",
  "    .paper-actions {",
  "      display: flex;",
  "      flex-wrap: wrap;",
  "      gap: 8px;",
  "      align-items: center;",
  "    }",
  "",
  "    .paper-comments {",
  "      border-top: 1px solid var(--line);",
  "      padding-top: 10px;",
  "      display: grid;",
  "      gap: 8px;",
  "    }",
  "",
  "    .comment-list {",
  "      margin: 0;",
  "      padding: 0;",
  "      list-style: none;",
  "      display: grid;",
  "      gap: 7px;",
  "    }",
  "",
  "    .comment-item {",
  "      border: 1px solid var(--line);",
  "      border-radius: var(--radius-sm);",
  "      padding: 8px;",
  "      font-size: 13px;",
  "      line-height: 1.4;",
  "      background: var(--panel);",
  "      box-shadow: var(--shadow-xs);",
  "    }",
  "",
  "    .empty-note {",
  "      border: 1px dashed var(--line);",
  "      border-radius: var(--radius-sm);",
  "      padding: 12px;",
  "      text-align: center;",
  "      color: var(--muted);",
  "      font-size: 13px;",
  "      background: var(--panel);",
  "    }",
  "",
  "    .chat-wrap {",
  "      border: 1px solid var(--line);",
  "      border-radius: var(--radius);",
  "      background: var(--panel);",
  "      box-shadow: var(--shadow-xs);",
  "      display: grid;",
  "      grid-template-rows: minmax(280px, 1fr) auto;",
  "      min-height: 520px;",
  "    }",
  "",
  "    .chat-messages {",
  "      min-height: 0;",
  "      overflow-y: auto;",
  "      padding: 12px;",
  "      display: grid;",
  "      gap: 10px;",
  "      align-content: start;",
  "      background: var(--panel);",
  "      border-radius: calc(var(--radius) - 1px) calc(var(--radius) - 1px) 0 0;",
  "    }",
  "",
  "    .bubble {",
  "      max-width: min(780px, 100%);",
  "      border-radius: var(--radius-sm);",
  "      border: 1px solid var(--line);",
  "      padding: 10px 12px;",
  "      white-space: pre-wrap;",
  "      word-break: break-word;",
  "      font-size: 14px;",
  "      line-height: 1.5;",
  "      box-shadow: var(--shadow-xs);",
  "    }",
  "",
  "    .bubble.user {",
  "      justify-self: end;",
  "      background: var(--ink);",
  "      color: #fff;",
  "      border-color: var(--ink);",
  "    }",
  "",
  "    .bubble.assistant {",
  "      justify-self: start;",
  "      background: var(--panel);",
  "      color: var(--ink);",
  "    }",
  "",
  "    .chat-composer {",
  "      border-top: 1px solid var(--line);",
  "      padding: 10px;",
  "      display: grid;",
  "      grid-template-columns: 1fr auto;",
  "      gap: 8px;",
  "      align-items: end;",
  "    }",
  "",
  "    .chat-composer textarea {",
  "      border: 1px solid var(--line);",
  "      border-radius: var(--radius-sm);",
  "      min-height: 76px;",
  "      max-height: 220px;",
  "      resize: vertical;",
  "      padding: 10px;",
  "      width: 100%;",
  "      line-height: 1.45;",
  "    }",
  "",
  "    .text-small {",
  "      font-size: 12px;",
  "      color: var(--muted);",
  "    }",
  "",
  "    .stack {",
  "      display: grid;",
  "      gap: 10px;",
  "    }",
  "",
  "    .inline-link {",
  "      color: var(--ink);",
  "      text-decoration: underline;",
  "      text-underline-offset: 2px;",
  "      font-weight: 700;",
  "    }",
  "",
  "    .inline-link:hover { text-decoration: underline; }",
  ""
].join("\n");
