export const componentStyles = [
  "    .field textarea {",
  "      min-height: 88px;",
  "      resize: vertical;",
  "      line-height: 1.45;",
  "    }",
  "",
  "    .actions-row {",
  "      display: flex;",
  "      gap: 8px;",
  "      flex-wrap: wrap;",
  "      align-items: center;",
  "    }",
  "",
  "    .stat {",
  "      border: 1px solid var(--line);",
  "      border-radius: 12px;",
  "      background: linear-gradient(160deg, #fff 0%, #faf8f4 100%);",
  "      padding: 12px;",
  "      display: grid;",
  "      gap: 5px;",
  "    }",
  "",
  "    .stat .label {",
  "      color: var(--muted);",
  "      font-size: 11px;",
  "      text-transform: uppercase;",
  "      letter-spacing: 0.06em;",
  "      font-weight: 700;",
  "    }",
  "",
  "    .stat .value {",
  "      font-size: 22px;",
  "      line-height: 1;",
  "      font-weight: 700;",
  "      color: var(--ink);",
  "    }",
  "",
  "    .chips {",
  "      display: flex;",
  "      flex-wrap: wrap;",
  "      gap: 7px;",
  "    }",
  "",
  "    .chip {",
  "      display: inline-flex;",
  "      border: 1px solid var(--line);",
  "      border-radius: 999px;",
  "      padding: 5px 10px;",
  "      font-size: 11px;",
  "      color: var(--muted);",
  "      background: #fff;",
  "    }",
  "",
  "    .explorer-controls {",
  "      display: grid;",
  "      gap: 10px;",
  "      grid-template-columns: 2fr 1fr 1fr auto;",
  "      align-items: end;",
  "    }",
  "",
  "    .paper-grid {",
  "      display: grid;",
  "      gap: 10px;",
  "    }",
  "",
  "    .paper-card {",
  "      border: 1px solid var(--line);",
  "      border-radius: 12px;",
  "      padding: 12px;",
  "      background: #fff;",
  "      display: grid;",
  "      gap: 9px;",
  "    }",
  "",
  "    .paper-card h4 {",
  "      margin: 0;",
  "      font-size: 16px;",
  "      line-height: 1.35;",
  "    }",
  "",
  "    .paper-meta {",
  "      margin: 0;",
  "      color: var(--muted);",
  "      font-size: 12px;",
  "      display: flex;",
  "      gap: 7px;",
  "      flex-wrap: wrap;",
  "      align-items: center;",
  "    }",
  "",
  "    .paper-abstract {",
  "      margin: 0;",
  "      color: #2d2a25;",
  "      font-size: 14px;",
  "      line-height: 1.55;",
  "    }",
  "",
  "    .tier-badge {",
  "      border-radius: 999px;",
  "      padding: 4px 8px;",
  "      font-size: 10px;",
  "      font-weight: 700;",
  "      letter-spacing: 0.05em;",
  "      text-transform: uppercase;",
  "      border: 1px solid var(--line);",
  "      background: #fff;",
  "    }",
  "",
  "    .tier-FOUNDATIONAL { background: #eaf6f4; border-color: #c5e9e3; color: #0d635c; }",
  "    .tier-DEPTH { background: #f2f4fb; border-color: #d7ddf5; color: #364c9c; }",
  "    .tier-BACKGROUND { background: #f8f4ed; border-color: #e8dac1; color: #7f6734; }",
  "",
  "    .paper-actions {",
  "      display: flex;",
  "      flex-wrap: wrap;",
  "      gap: 8px;",
  "      align-items: center;",
  "    }",
  "",
  "    .paper-comments {",
  "      border-top: 1px solid var(--line);",
  "      padding-top: 10px;",
  "      display: grid;",
  "      gap: 8px;",
  "    }",
  "",
  "    .comment-list {",
  "      margin: 0;",
  "      padding: 0;",
  "      list-style: none;",
  "      display: grid;",
  "      gap: 7px;",
  "    }",
  "",
  "    .comment-item {",
  "      border: 1px solid var(--line);",
  "      border-radius: 10px;",
  "      padding: 8px;",
  "      font-size: 13px;",
  "      line-height: 1.4;",
  "      background: #fcfbf8;",
  "    }",
  "",
  "    .empty-note {",
  "      border: 1px dashed var(--line);",
  "      border-radius: 12px;",
  "      padding: 12px;",
  "      text-align: center;",
  "      color: var(--muted);",
  "      font-size: 13px;",
  "      background: #fff;",
  "    }",
  "",
  "    .chat-wrap {",
  "      border: 1px solid var(--line);",
  "      border-radius: var(--radius);",
  "      background: #fff;",
  "      display: grid;",
  "      grid-template-rows: minmax(280px, 1fr) auto;",
  "      min-height: 520px;",
  "    }",
  "",
  "    .chat-messages {",
  "      min-height: 0;",
  "      overflow-y: auto;",
  "      padding: 12px;",
  "      display: grid;",
  "      gap: 10px;",
  "      align-content: start;",
  "      background: linear-gradient(180deg, #fffefd 0%, #f8f5ef 100%);",
  "      border-radius: 13px 13px 0 0;",
  "    }",
  "",
  "    .bubble {",
  "      max-width: min(780px, 100%);",
  "      border-radius: 12px;",
  "      border: 1px solid var(--line);",
  "      padding: 10px 12px;",
  "      white-space: pre-wrap;",
  "      word-break: break-word;",
  "      font-size: 14px;",
  "      line-height: 1.5;",
  "    }",
  "",
  "    .bubble.user {",
  "      justify-self: end;",
  "      background: var(--ink);",
  "      color: #fff;",
  "      border-color: var(--ink);",
  "    }",
  "",
  "    .bubble.assistant {",
  "      justify-self: start;",
  "      background: #fff;",
  "      color: var(--ink);",
  "    }",
  "",
  "    .chat-composer {",
  "      border-top: 1px solid var(--line);",
  "      padding: 10px;",
  "      display: grid;",
  "      grid-template-columns: 1fr auto;",
  "      gap: 8px;",
  "      align-items: end;",
  "    }",
  "",
  "    .chat-composer textarea {",
  "      border: 1px solid var(--line);",
  "      border-radius: 10px;",
  "      min-height: 76px;",
  "      max-height: 220px;",
  "      resize: vertical;",
  "      padding: 10px;",
  "      width: 100%;",
  "      line-height: 1.45;",
  "    }",
  "",
  "    .text-small {",
  "      font-size: 12px;",
  "      color: var(--muted);",
  "    }",
  "",
  "    .stack {",
  "      display: grid;",
  "      gap: 10px;",
  "    }",
  "",
  "    .inline-link {",
  "      color: var(--accent);",
  "      text-decoration: none;",
  "      font-weight: 700;",
  "    }",
  "",
  "    .inline-link:hover { text-decoration: underline; }",
  ""
].join("\n");
