export const layoutStyles = [
  "",
  "    .project-node.active {",
  "      border-color: #c9c0b3;",
  "      box-shadow: 0 8px 20px rgba(18, 15, 11, 0.06);",
  "    }",
  "",
  "    .project-trigger {",
  "      width: 100%;",
  "      border: none;",
  "      background: transparent;",
  "      text-align: left;",
  "      padding: 11px;",
  "      cursor: pointer;",
  "      display: grid;",
  "      gap: 4px;",
  "      color: var(--ink);",
  "    }",
  "",
  "    .project-trigger:hover {",
  "      background: var(--soft);",
  "    }",
  "",
  "    .project-title {",
  "      font-size: 14px;",
  "      font-weight: 700;",
  "      line-height: 1.3;",
  "      white-space: nowrap;",
  "      overflow: hidden;",
  "      text-overflow: ellipsis;",
  "    }",
  "",
  "    .project-meta {",
  "      font-size: 11px;",
  "      color: var(--muted);",
  "      display: flex;",
  "      gap: 6px;",
  "      flex-wrap: wrap;",
  "      align-items: center;",
  "    }",
  "",
  "    .dot {",
  "      width: 4px;",
  "      height: 4px;",
  "      border-radius: 999px;",
  "      background: #a9a399;",
  "      display: inline-block;",
  "    }",
  "",
  "    .project-children {",
  "      border-top: 1px solid var(--line);",
  "      background: #fcfbf9;",
  "      padding: 8px;",
  "      display: grid;",
  "      gap: 6px;",
  "    }",
  "",
  "    .subnav-btn,",
  "    .chat-btn {",
  "      width: 100%;",
  "      text-align: left;",
  "      border: 1px solid transparent;",
  "      border-radius: 10px;",
  "      padding: 9px 10px;",
  "      background: transparent;",
  "      cursor: pointer;",
  "      color: var(--ink);",
  "      font-size: 13px;",
  "      line-height: 1.3;",
  "    }",
  "",
  "    .subnav-btn:hover,",
  "    .chat-btn:hover { background: #f3f0ea; }",
  "",
  "    .subnav-btn.active,",
  "    .chat-btn.active {",
  "      background: var(--accent-soft);",
  "      border-color: #b7e2dc;",
  "      color: #0b564f;",
  "      font-weight: 700;",
  "    }",
  "",
  "    .chat-list {",
  "      display: grid;",
  "      gap: 6px;",
  "      margin-top: 4px;",
  "    }",
  "",
  "    .chat-empty {",
  "      border: 1px dashed var(--line);",
  "      border-radius: 10px;",
  "      padding: 10px;",
  "      font-size: 12px;",
  "      color: var(--muted);",
  "      text-align: center;",
  "    }",
  "",
  "    .user-email {",
  "      font-weight: 700;",
  "      color: var(--ink);",
  "      white-space: nowrap;",
  "      overflow: hidden;",
  "      text-overflow: ellipsis;",
  "    }",
  "",
  "    .main {",
  "      display: grid;",
  "      grid-template-rows: auto minmax(0, 1fr);",
  "      min-height: 0;",
  "    }",
  "",
  "    .main-head {",
  "      border-bottom: 1px solid var(--line);",
  "      padding: 18px 20px;",
  "      display: grid;",
  "      grid-template-columns: minmax(0, 1fr) auto;",
  "      gap: 12px;",
  "      align-items: start;",
  "      background: rgba(255, 255, 255, 0.85);",
  "    }",
  "",
  "    .main-head h2 {",
  "      margin: 0;",
  "      font-family: \"Newsreader\", Georgia, serif;",
  "      font-size: clamp(25px, 2.5vw, 33px);",
  "      line-height: 1.1;",
  "      letter-spacing: -0.02em;",
  "      font-weight: 700;",
  "    }",
  "",
  "    .main-head p {",
  "      margin: 6px 0 0;",
  "      color: var(--muted);",
  "      font-size: 13px;",
  "      max-width: 66ch;",
  "    }",
  "",
  "    .main-actions {",
  "      display: flex;",
  "      flex-wrap: wrap;",
  "      gap: 8px;",
  "      justify-content: end;",
  "    }",
  "",
  "    .main-content {",
  "      min-height: 0;",
  "      overflow-y: auto;",
  "      padding: 18px;",
  "      display: grid;",
  "      gap: 14px;",
  "      align-content: start;",
  "    }",
  "",
  "    .panel {",
  "      border: 1px solid var(--line);",
  "      border-radius: var(--radius);",
  "      background: #fff;",
  "      padding: 14px;",
  "      display: grid;",
  "      gap: 10px;",
  "    }",
  "",
  "    .panel h3 {",
  "      margin: 0;",
  "      font-size: 16px;",
  "      line-height: 1.25;",
  "    }",
  "",
  "    .panel p {",
  "      margin: 0;",
  "      color: var(--muted);",
  "      font-size: 13px;",
  "      line-height: 1.55;",
  "    }",
  "",
  "    .grid.two {",
  "      display: grid;",
  "      gap: 10px;",
  "      grid-template-columns: repeat(2, minmax(0, 1fr));",
  "    }",
  "",
  "    .grid.four {",
  "      display: grid;",
  "      gap: 10px;",
  "      grid-template-columns: repeat(4, minmax(0, 1fr));",
  "    }",
  "",
  "    .field {",
  "      display: grid;",
  "      gap: 6px;",
  "    }",
  "",
  "    .field label {",
  "      font-size: 12px;",
  "      font-weight: 700;",
  "      color: var(--muted);",
  "      text-transform: uppercase;",
  "      letter-spacing: 0.03em;",
  "    }",
  "",
  "    .field input,",
  "    .field textarea,",
  "    .field select {",
  "      width: 100%;",
  "      border: 1px solid var(--line);",
  "      border-radius: 10px;",
  "      padding: 10px;",
  "      color: var(--ink);",
  "      background: #fff;",
  "    }"
].join("\n");
