export const responsiveStyles = [
  "    @media (max-width: 1120px) {",
  "      .app-shell {",
  "        grid-template-columns: 1fr;",
  "        grid-template-rows: auto minmax(0, 1fr);",
  "      }",
  "",
  "      .project-tree {",
  "        max-height: 280px;",
  "      }",
  "",
  "      .grid.four {",
  "        grid-template-columns: repeat(2, minmax(0, 1fr));",
  "      }",
  "",
  "      .explorer-controls {",
  "        grid-template-columns: 1fr 1fr;",
  "      }",
  "    }",
  "",
  "    @media (max-width: 700px) {",
  "      .app-shell { padding: 8px; gap: 8px; }",
  "      .sidebar-head, .sidebar-foot, .main-head, .main-content { padding: 12px; }",
  "      .grid.two, .grid.four { grid-template-columns: 1fr; }",
  "      .chat-composer { grid-template-columns: 1fr; }",
  "      .main-actions { justify-content: start; }",
  "    }"
].join("\n");
