export const chatScript = [
  "    async function renderReadingList(project) {",
  "      setHeader(projectTitle(project), \"Reading List\", []);",
  "      const payload = await api(\"/api/projects/\" + project.id + \"/reading-list\");",
  "      const papers = payload.papers || [];",
  "",
  "      const content = byId(\"mainContent\");",
  "      content.innerHTML =",
  "        '<section class=\"paper-grid\">' +",
  "          (papers.length === 0",
  "            ? '<p class=\"empty-note\">Your reading list is empty. Add papers from the explorer.</p>'",
  "            : papers.map((paper) => {",
  "              return '<article class=\"paper-card\">' +",
  "                '<h4>' + escapeHtml(paper.title) + '</h4>' +",
  "                '<p class=\"paper-meta\">' +",
  "                  '<span>' + escapeHtml(paper.year || \"Year n/a\") + '</span>' +",
  "                  '<span class=\"dot\"></span>' +",
  "                  '<span>' + escapeHtml((paper.citationCount || 0) + \" citations\") + '</span>' +",
  "                  '<span class=\"dot\"></span>' +",
  "                  '<span class=\"tier-badge tier-' + escapeHtml(paper.tier || \"BACKGROUND\") + '\">' + escapeHtml(paper.tier || \"MANUAL\") + '</span>' +",
  "                '</p>' +",
  "                '<form class=\"reading-form\" data-paper-id=\"' + escapeHtml(paper.id) + '\">' +",
  "                  '<div class=\"field\"><label>Tags (comma-separated)</label><input name=\"tags\" value=\"' + escapeHtml((paper.tags || []).join(\", \")) + '\" /></div>' +",
  "                  '<div class=\"field\"><label>Comments</label><textarea name=\"comment\">' + escapeHtml(paper.comment || paper.note || \"\") + '</textarea></div>' +",
  "                  '<div class=\"actions-row\">' +",
  "                    '<button type=\"submit\" class=\"button soft\">Save comments</button>' +",
  "                    '<button type=\"button\" class=\"button soft\" data-action=\"toggle-bookmark\" data-paper-id=\"' + escapeHtml(paper.id) + '\" data-current=\"' + (paper.bookmarked ? \"1\" : \"0\") + '\">' + (paper.bookmarked ? \"Bookmarked\" : \"Bookmark\") + '</button>' +",
  "                    '<button type=\"button\" class=\"button danger\" data-action=\"remove-reading\" data-paper-id=\"' + escapeHtml(paper.id) + '\">Remove from list</button>' +",
  "                    (paper.access && paper.access.pdfUrl",
  "                      ? '<a class=\"inline-link\" target=\"_blank\" rel=\"noopener noreferrer\" href=\"' + escapeHtml(paper.access.pdfUrl) + '\">Open PDF</a>'",
  "                      : \"\") +",
  "                  '</div>' +",
  "                '</form>' +",
  "              '</article>';",
  "            }).join(\"\")) +",
  "        '</section>';",
  "",
  "      content.querySelectorAll(\".reading-form\").forEach((form) => {",
  "        form.addEventListener(\"submit\", async (event) => {",
  "          event.preventDefault();",
  "          const formNode = event.currentTarget;",
  "          const paperId = formNode.getAttribute(\"data-paper-id\");",
  "          const comment = formNode.querySelector('textarea[name=\"comment\"]').value.trim();",
  "          const tags = decodeListInput(formNode.querySelector('input[name=\"tags\"]').value);",
  "          if (!paperId) {",
  "            return;",
  "          }",
  "          try {",
  "            await api(\"/api/projects/\" + project.id + \"/papers/\" + paperId, {",
  "              method: \"PATCH\",",
  "              body: JSON.stringify({ comment, tags })",
  "            });",
  "            await renderReadingList(project);",
  "          } catch (error) {",
  "            showError(error);",
  "          }",
  "        });",
  "      });",
  "",
  "      content.querySelectorAll(\"button[data-action]\").forEach((button) => {",
  "        button.addEventListener(\"click\", async (event) => {",
  "          const action = event.currentTarget.getAttribute(\"data-action\");",
  "          const paperId = event.currentTarget.getAttribute(\"data-paper-id\");",
  "          if (!paperId) {",
  "            return;",
  "          }",
  "          try {",
  "            if (action === \"remove-reading\") {",
  "              await api(\"/api/projects/\" + project.id + \"/papers/\" + paperId, {",
  "                method: \"PATCH\",",
  "                body: JSON.stringify({ inReadingList: false })",
  "              });",
  "              await loadProjects();",
  "              return;",
  "            }",
  "            if (action === \"toggle-bookmark\") {",
  "              const current = event.currentTarget.getAttribute(\"data-current\") === \"1\";",
  "              await api(\"/api/projects/\" + project.id + \"/papers/\" + paperId, {",
  "                method: \"PATCH\",",
  "                body: JSON.stringify({ bookmarked: !current })",
  "              });",
  "              await renderReadingList(project);",
  "            }",
  "          } catch (error) {",
  "            showError(error);",
  "          }",
  "        });",
  "      });",
  "    }",
  "",
  "    async function renderChat(project) {",
  "      await ensureChats(project.id, false);",
  "      const chats = state.chatsByProject.get(project.id) || [];",
  "      if (!state.activeChatId && chats.length > 0) {",
  "        state.activeChatId = chats[0].id;",
  "      }",
  "",
  "      const activeChat = chats.find((chat) => chat.id === state.activeChatId) || null;",
  "      if (!activeChat) {",
  "        setHeader(projectTitle(project), \"Chats\", [",
  "          makeButton(\"New chat\", \"accent\", async () => {",
  "            try {",
  "              await createChat(project.id);",
  "            } catch (error) {",
  "              showError(error);",
  "            }",
  "          })",
  "        ]);",
  "        const content = byId(\"mainContent\");",
  "        content.innerHTML =",
  "          '<article class=\"panel\">' +",
  "            '<h3>Start a chat</h3>' +",
  "            '<p>Open a chat for any purpose: debating your thesis, planning work, interpreting papers, or writing sections.</p>' +",
  "            '<div class=\"actions-row\"><button id=\"startChatButton\" class=\"button accent\" type=\"button\">Create chat</button></div>' +",
  "          '</article>';",
  "        byId(\"startChatButton\").addEventListener(\"click\", async () => {",
  "          try {",
  "            await createChat(project.id);",
  "          } catch (error) {",
  "            showError(error);",
  "          }",
  "        });",
  "        return;",
  "      }",
  "",
  "      setHeader(projectTitle(project), activeChat.title, [",
  "        makeButton(\"Rename chat\", \"soft\", async () => {",
  "          const nextTitle = prompt(\"Rename chat\", activeChat.title);",
  "          if (!nextTitle || !nextTitle.trim()) {",
  "            return;",
  "          }",
  "          try {",
  "            await api(\"/api/projects/\" + project.id + \"/chats/\" + activeChat.id, {",
  "              method: \"PATCH\",",
  "              body: JSON.stringify({ title: nextTitle.trim() })",
  "            });",
  "            await ensureChats(project.id, true);",
  "            renderSidebar();",
  "            await renderChat(project);",
  "          } catch (error) {",
  "            showError(error);",
  "          }",
  "        }),",
  "        makeButton(\"Delete chat\", \"danger\", async () => {",
  "          if (!confirm(\"Delete this chat?\")) {",
  "            return;",
  "          }",
  "          try {",
  "            await api(\"/api/projects/\" + project.id + \"/chats/\" + activeChat.id, {",
  "              method: \"DELETE\"",
  "            });",
  "            state.messagesByChat.delete(activeChat.id);",
  "            state.activeChatId = null;",
  "            await ensureChats(project.id, true);",
  "            renderSidebar();",
  "            await renderChat(project);",
  "          } catch (error) {",
  "            showError(error);",
  "          }",
  "        })",
  "      ]);",
  "",
  "      const messagesPayload = await api(\"/api/projects/\" + project.id + \"/chats/\" + activeChat.id + \"/messages\");",
  "      const messages = messagesPayload.messages || [];",
  "      state.messagesByChat.set(activeChat.id, messages);",
  "",
  "      const content = byId(\"mainContent\");",
  "      content.innerHTML =",
  "        '<section class=\"chat-wrap\">' +",
  "          '<div id=\"chatMessages\" class=\"chat-messages\">' +",
  "            (messages.length === 0",
  "              ? '<p class=\"empty-note\">No messages yet. Start the conversation.</p>'",
  "              : messages.map((message) =>",
  "                  '<article class=\"bubble ' + escapeHtml(message.role === \"user\" ? \"user\" : \"assistant\") + '\">' + escapeHtml(message.content) + '</article>'",
  "                ).join(\"\")) +",
  "          '</div>' +",
  "          '<form id=\"chatComposer\" class=\"chat-composer\">' +",
  "            '<textarea id=\"chatInput\" placeholder=\"Write anything about your thesis, your findings, or your next plan.\" required></textarea>' +",
  "            '<button id=\"chatSendButton\" type=\"submit\" class=\"button accent\">Send</button>' +",
  "          '</form>' +",
  "        '</section>';",
  "",
  "      const chatMessages = byId(\"chatMessages\");",
  "      chatMessages.scrollTop = chatMessages.scrollHeight;",
  "",
  "      byId(\"chatComposer\").addEventListener(\"submit\", async (event) => {",
  "        event.preventDefault();",
  "        if (state.sendingMessage) {",
  "          return;",
  "        }",
  "        const input = byId(\"chatInput\");",
  "        const text = input.value.trim();",
  "        if (!text) {",
  "          return;",
  "        }",
  "",
  "        state.sendingMessage = true;",
  "        const sendButton = byId(\"chatSendButton\");",
  "        sendButton.disabled = true;",
  "        sendButton.textContent = \"Sending...\";",
  "        try {",
  "          await api(\"/api/projects/\" + project.id + \"/chats/\" + activeChat.id + \"/messages\", {",
  "            method: \"POST\",",
  "            body: JSON.stringify({ content: text })",
  "          });",
  "          input.value = \"\";",
  "          await ensureChats(project.id, true);",
  "          renderSidebar();",
  "          await renderChat(project);",
  "        } catch (error) {",
  "          showError(error);",
  "        } finally {",
  "          state.sendingMessage = false;",
  "          sendButton.disabled = false;",
  "          sendButton.textContent = \"Send\";",
  "        }",
  "      });",
  "    }",
  "",
  "    byId(\"newProjectButton\").addEventListener(\"click\", async () => {",
  "      state.activeView = \"new-project\";",
  "      state.activeChatId = null;",
  "      renderSidebar();",
  "      await renderMain();",
  "    });",
  "",
  "    byId(\"logoutButton\").addEventListener(\"click\", async () => {",
  "      try {",
  "        await api(\"/api/auth/logout\", { method: \"POST\" });",
  "      } catch {",
  "        // best effort logout",
  "      }",
  "      state.user = null;",
  "      state.projects = [];",
  "      state.chatsByProject = new Map();",
  "      state.dashboardByProject = new Map();",
  "      state.messagesByChat = new Map();",
  "      state.commentsByPaper = new Map();",
  "      state.openComments = new Set();",
  "      state.activeProjectId = null;",
  "      state.activeChatId = null;",
  "      state.activeView = \"new-project\";",
  "      stopPolling();",
  "      showLanding();",
  "    });",
  "",
  "    async function boot() {",
  "      await loadAuth();",
  "    }",
  "",
  "    boot().catch(showError);"
].join("\n");
