export const coreScript = [
  "    const state = {",
  "      user: null,",
  "      projects: [],",
  "      chatsByProject: new Map(),",
  "      dashboardByProject: new Map(),",
  "      messagesByChat: new Map(),",
  "      commentsByPaper: new Map(),",
  "      openComments: new Set(),",
  "      activeProjectId: null,",
  "      activeView: \"new-project\",",
  "      activeChatId: null,",
  "      explorerFilters: {",
  "        query: \"\",",
  "        sort: \"relevance\",",
  "        tier: \"\",",
  "        oaOnly: false,",
  "        bookmarkedOnly: false",
  "      },",
  "      pollTimer: null,",
  "      pollInFlight: false,",
  "      sendingMessage: false",
  "    };",
  "",
  "    const byId = (id) => document.getElementById(id);",
  "    const clearNode = (node) => node.replaceChildren();",
  "",
  "    function escapeHtml(value) {",
  "      return String(value || \"\")",
  "        .replace(/&/g, \"&amp;\")",
  "        .replace(/</g, \"&lt;\")",
  "        .replace(/>/g, \"&gt;\")",
  "        .replace(/\\\"/g, \"&quot;\")",
  "        .replace(/'/g, \"&#39;\");",
  "    }",
  "",
  "    function formatDate(value) {",
  "      if (!value) {",
  "        return \"\";",
  "      }",
  "      try {",
  "        return new Date(value).toLocaleString();",
  "      } catch {",
  "        return value;",
  "      }",
  "    }",
  "",
  "    function projectTitle(project) {",
  "      const raw = typeof project.title === \"string\" ? project.title.trim() : \"\";",
  "      if (raw) {",
  "        return raw;",
  "      }",
  "      return \"Project \" + project.id.slice(0, 8);",
  "    }",
  "",
  "    function projectStatusLabel(project) {",
  "      const status = project && project.latestRun ? project.latestRun.status : null;",
  "      if (status === \"RUNNING\" || status === \"QUEUED\") {",
  "        return \"Updating suggestions\";",
  "      }",
  "      if (status === \"FAILED\") {",
  "        return \"Needs another pass\";",
  "      }",
  "      if (status === \"COMPLETED\") {",
  "        return \"Suggestions ready\";",
  "      }",
  "      return \"Ready\";",
  "    }",
  "",
  "    function isProjectUpdating(project) {",
  "      const status = project && project.latestRun ? project.latestRun.status : null;",
  "      return status === \"RUNNING\" || status === \"QUEUED\";",
  "    }",
  "",
  "    async function api(path, options = {}) {",
  "      const response = await fetch(path, {",
  "        ...options,",
  "        credentials: \"same-origin\",",
  "        headers: {",
  "          \"content-type\": \"application/json\",",
  "          ...(options.headers || {})",
  "        }",
  "      });",
  "",
  "      const isJson = (response.headers.get(\"content-type\") || \"\").includes(\"application/json\");",
  "      const payload = isJson ? await response.json() : await response.text();",
  "      if (!response.ok) {",
  "        const message = typeof payload === \"string\" ? payload : payload.error || \"Request failed\";",
  "        throw new Error(message);",
  "      }",
  "      return payload;",
  "    }",
  "",
  "    function showError(error) {",
  "      alert(error && error.message ? error.message : String(error));",
  "    }",
  "",
  "    function showLanding() {",
  "      byId(\"landingView\").classList.remove(\"hidden\");",
  "      byId(\"appView\").classList.add(\"hidden\");",
  "      stopPolling();",
  "    }",
  "",
  "    function showApp() {",
  "      byId(\"landingView\").classList.add(\"hidden\");",
  "      byId(\"appView\").classList.remove(\"hidden\");",
  "    }",
  "",
  "    function stopPolling() {",
  "      if (state.pollTimer) {",
  "        clearInterval(state.pollTimer);",
  "        state.pollTimer = null;",
  "      }",
  "    }",
  "",
  "    function restartPolling() {",
  "      stopPolling();",
  "      const hasPending = state.projects.some((project) => isProjectUpdating(project));",
  "      if (!hasPending) {",
  "        return;",
  "      }",
  "      state.pollTimer = setInterval(async () => {",
  "        if (state.pollInFlight) {",
  "          return;",
  "        }",
  "        state.pollInFlight = true;",
  "        try {",
  "          await loadProjects();",
  "        } catch {",
  "          // transient polling errors are expected",
  "        } finally {",
  "          state.pollInFlight = false;",
  "        }",
  "      }, 5000);",
  "    }",
  "",
  "    async function loadAuth() {",
  "      try {",
  "        const data = await api(\"/api/auth/me\");",
  "        state.user = data.user;",
  "      } catch {",
  "        state.user = null;",
  "      }",
  "",
  "      if (!state.user) {",
  "        showLanding();",
  "        return;",
  "      }",
  "",
  "      showApp();",
  "      byId(\"userEmail\").textContent = state.user.email;",
  "      await loadProjects();",
  "    }",
  "",
  "    async function ensureChats(projectId, force) {",
  "      if (!projectId) {",
  "        return;",
  "      }",
  "      if (!force && state.chatsByProject.has(projectId)) {",
  "        return;",
  "      }",
  "      const payload = await api(\"/api/projects/\" + projectId + \"/chats\");",
  "      const chats = payload.chats || [];",
  "      state.chatsByProject.set(projectId, chats);",
  "      if (state.activeChatId && !chats.some((chat) => chat.id === state.activeChatId)) {",
  "        state.activeChatId = null;",
  "      }",
  "    }",
  "",
  "    async function loadProjects() {",
  "      const payload = await api(\"/api/projects\");",
  "      state.projects = payload.projects || [];",
  "",
  "      if (!state.activeProjectId && state.projects.length > 0) {",
  "        state.activeProjectId = state.projects[0].id;",
  "        if (state.activeView === \"new-project\") {",
  "          state.activeView = \"dashboard\";",
  "        }",
  "      }",
  "",
  "      if (state.activeProjectId && !state.projects.some((project) => project.id === state.activeProjectId)) {",
  "        state.activeProjectId = state.projects.length > 0 ? state.projects[0].id : null;",
  "        state.activeChatId = null;",
  "      }",
  "",
  "      if (!state.activeProjectId) {",
  "        state.activeView = \"new-project\";",
  "      }",
  "",
  "      if (state.activeProjectId) {",
  "        await ensureChats(state.activeProjectId, false);",
  "      }",
  "",
  "      renderSidebar();",
  "      await renderMain();",
  "      restartPolling();",
  "    }",
  "",
  "    function setHeader(title, subtitle, actions) {",
  "      byId(\"mainTitle\").textContent = title;",
  "      byId(\"mainSubtitle\").textContent = subtitle || \"\";",
  "      const actionsNode = byId(\"mainActions\");",
  "      clearNode(actionsNode);",
  "      (actions || []).forEach((button) => actionsNode.append(button));",
  "    }",
  "",
  "    function makeButton(label, className, onClick) {",
  "      const button = document.createElement(\"button\");",
  "      button.type = \"button\";",
  "      button.className = \"button \" + (className || \"soft\");",
  "      button.textContent = label;",
  "      button.addEventListener(\"click\", onClick);",
  "      return button;",
  "    }",
  ""
].join("\n");
