export const explorerScript = [
  "    async function renderExplorer(project) {",
  "      const actions = [",
  "        makeButton(\"Refresh suggestions\", \"soft\", async () => {",
  "          try {",
  "            await api(\"/api/projects/\" + project.id + \"/runs\", { method: \"POST\" });",
  "            await loadProjects();",
  "          } catch (error) {",
  "            showError(error);",
  "          }",
  "        })",
  "      ];",
  "      setHeader(projectTitle(project), \"Paper Explorer\", actions);",
  "",
  "      const filters = state.explorerFilters;",
  "      const params = new URLSearchParams();",
  "      if (filters.query) params.set(\"query\", filters.query);",
  "      if (filters.sort) params.set(\"sort\", filters.sort);",
  "      if (filters.tier) params.set(\"tier\", filters.tier);",
  "      if (filters.oaOnly) params.set(\"oaOnly\", \"true\");",
  "      if (filters.bookmarkedOnly) params.set(\"bookmarkedOnly\", \"true\");",
  "",
  "      const payload = await api(\"/api/projects/\" + project.id + \"/papers?\" + params.toString());",
  "      const papers = payload.papers || [];",
  "",
  "      const content = byId(\"mainContent\");",
  "      content.innerHTML =",
  "        '<article class=\"panel\">' +",
  "          '<form id=\"explorerFiltersForm\" class=\"stack\">' +",
  "            '<div class=\"explorer-controls\">' +",
  "              '<div class=\"field\"><label>Search</label><input name=\"query\" value=\"' + escapeHtml(filters.query) + '\" placeholder=\"Title, abstract, DOI\" /></div>' +",
  "              '<div class=\"field\"><label>Sort</label><select name=\"sort\">' +",
  "                '<option value=\"relevance\"' + (filters.sort === \"relevance\" ? \" selected\" : \"\") + '>Most relevant</option>' +",
  "                '<option value=\"recent\"' + (filters.sort === \"recent\" ? \" selected\" : \"\") + '>Recent</option>' +",
  "                '<option value=\"citations\"' + (filters.sort === \"citations\" ? \" selected\" : \"\") + '>Citations</option>' +",
  "                '<option value=\"newest\"' + (filters.sort === \"newest\" ? \" selected\" : \"\") + '>Recently added</option>' +",
  "              '</select></div>' +",
  "              '<div class=\"field\"><label>Tier</label><select name=\"tier\">' +",
  "                '<option value=\"\">All tiers</option>' +",
  "                '<option value=\"FOUNDATIONAL\"' + (filters.tier === \"FOUNDATIONAL\" ? \" selected\" : \"\") + '>Foundational</option>' +",
  "                '<option value=\"DEPTH\"' + (filters.tier === \"DEPTH\" ? \" selected\" : \"\") + '>Depth</option>' +",
  "                '<option value=\"BACKGROUND\"' + (filters.tier === \"BACKGROUND\" ? \" selected\" : \"\") + '>Background</option>' +",
  "              '</select></div>' +",
  "              '<div class=\"actions-row\">' +",
  "                '<button class=\"button soft\" type=\"submit\">Apply</button>' +",
  "              '</div>' +",
  "            '</div>' +",
  "            '<div class=\"actions-row\">' +",
  "              '<label><input type=\"checkbox\" name=\"oaOnly\"' + (filters.oaOnly ? \" checked\" : \"\") + '> Open access only</label>' +",
  "              '<label><input type=\"checkbox\" name=\"bookmarkedOnly\"' + (filters.bookmarkedOnly ? \" checked\" : \"\") + '> Bookmarked only</label>' +",
  "              '<span class=\"text-small\">Sorting by: ' + escapeHtml(mapSortLabel(filters.sort)) + '</span>' +",
  "            '</div>' +",
  "          '</form>' +",
  "        '</article>' +",
  "        '<article class=\"panel\">' +",
  "          '<h3>Add a paper manually</h3>' +",
  "          '<p>You can add papers discovered outside chat and keep them in the same project explorer.</p>' +",
  "          '<form id=\"addPaperForm\" class=\"stack\">' +",
  "            '<div class=\"grid two\">' +",
  "              '<div class=\"field\"><label>Title *</label><input name=\"title\" required /></div>' +",
  "              '<div class=\"field\"><label>DOI</label><input name=\"doi\" /></div>' +",
  "            '</div>' +",
  "            '<div class=\"grid two\">' +",
  "              '<div class=\"field\"><label>Year</label><input name=\"year\" type=\"number\" min=\"1900\" max=\"2100\" /></div>' +",
  "              '<div class=\"field\"><label>Citation count</label><input name=\"citationCount\" type=\"number\" min=\"0\" /></div>' +",
  "            '</div>' +",
  "            '<div class=\"field\"><label>Fields of study (comma-separated)</label><input name=\"fields\" placeholder=\"Economics, Computer Science\" /></div>' +",
  "            '<div class=\"field\"><label>Abstract</label><textarea name=\"abstract\"></textarea></div>' +",
  "            '<div class=\"actions-row\"><button type=\"submit\" class=\"button accent\">Add paper</button></div>' +",
  "          '</form>' +",
  "        '</article>' +",
  "        '<section class=\"paper-grid\">' +",
  "          (papers.length === 0",
  "            ? '<p class=\"empty-note\">No papers match your current filters.</p>'",
  "            : papers.map((paper) => {",
  "              const links = [];",
  "              if (paper.access && paper.access.pdfUrl) {",
  "                links.push('<a class=\"inline-link\" target=\"_blank\" rel=\"noopener noreferrer\" href=\"' + escapeHtml(paper.access.pdfUrl) + '\">Open PDF</a>');",
  "              }",
  "              if (paper.doi) {",
  "                links.push('<a class=\"inline-link\" target=\"_blank\" rel=\"noopener noreferrer\" href=\"https://doi.org/' + encodeURIComponent(paper.doi) + '\">DOI</a>');",
  "              }",
  "              const comments = state.commentsByPaper.get(paper.id) || [];",
  "              const commentsOpen = state.openComments.has(paper.id);",
  "              return '<article class=\"paper-card\">' +",
  "                '<h4>' + escapeHtml(paper.title) + '</h4>' +",
  "                '<p class=\"paper-meta\">' +",
  "                  '<span>' + escapeHtml(paper.year || \"Year n/a\") + '</span>' +",
  "                  '<span class=\"dot\"></span>' +",
  "                  '<span>' + escapeHtml((paper.citationCount || 0) + \" citations\") + '</span>' +",
  "                  '<span class=\"dot\"></span>' +",
  "                  '<span class=\"tier-badge tier-' + escapeHtml(paper.tier || \"BACKGROUND\") + '\">' + escapeHtml(paper.tier || \"MANUAL\") + '</span>' +",
  "                '</p>' +",
  "                '<p class=\"paper-abstract\">' + escapeHtml((paper.abstract || \"No abstract available.\").slice(0, 340)) + '</p>' +",
  "                '<div class=\"paper-actions\">' +",
  "                  '<button class=\"button soft\" type=\"button\" data-action=\"toggle-bookmark\" data-paper-id=\"' + escapeHtml(paper.id) + '\" data-current=\"' + (paper.bookmarked ? \"1\" : \"0\") + '\">' + (paper.bookmarked ? \"Bookmarked\" : \"Bookmark\") + '</button>' +",
  "                  '<button class=\"button soft\" type=\"button\" data-action=\"toggle-reading\" data-paper-id=\"' + escapeHtml(paper.id) + '\" data-current=\"' + (paper.inReadingList ? \"1\" : \"0\") + '\">' + (paper.inReadingList ? \"In reading list\" : \"Add to reading list\") + '</button>' +",
  "                  '<button class=\"button soft\" type=\"button\" data-action=\"toggle-comments\" data-paper-id=\"' + escapeHtml(paper.id) + '\">' + (commentsOpen ? \"Hide comments\" : \"Comments\") + ' (' + escapeHtml(paper.commentCount || 0) + ')</button>' +",
  "                  '<button class=\"button danger\" type=\"button\" data-action=\"delete-paper\" data-paper-id=\"' + escapeHtml(paper.id) + '\">Remove</button>' +",
  "                  links.join(\" \") +",
  "                '</div>' +",
  "                (commentsOpen",
  "                  ? '<div class=\"paper-comments\">' +",
  "                      '<ul class=\"comment-list\">' +",
  "                        (comments.length === 0",
  "                          ? '<li class=\"comment-item\">No comments yet.</li>'",
  "                          : comments.map((comment) =>",
  "                              '<li class=\"comment-item\">' +",
  "                                '<div>' + escapeHtml(comment.body) + '</div>' +",
  "                                '<div class=\"text-small\">' + escapeHtml(formatDate(comment.createdAt)) + '</div>' +",
  "                              '</li>'",
  "                            ).join(\"\")) +",
  "                      '</ul>' +",
  "                      '<form class=\"comment-form\" data-paper-id=\"' + escapeHtml(paper.id) + '\">' +",
  "                        '<div class=\"field\"><label>Add comment</label><textarea name=\"body\" required></textarea></div>' +",
  "                        '<div class=\"actions-row\"><button type=\"submit\" class=\"button soft\">Save comment</button></div>' +",
  "                      '</form>' +",
  "                    '</div>'",
  "                  : \"\") +",
  "              '</article>';",
  "            }).join(\"\")) +",
  "        '</section>';",
  "",
  "      byId(\"explorerFiltersForm\").addEventListener(\"submit\", async (event) => {",
  "        event.preventDefault();",
  "        const form = event.currentTarget;",
  "        state.explorerFilters.query = form.query.value.trim();",
  "        state.explorerFilters.sort = form.sort.value;",
  "        state.explorerFilters.tier = form.tier.value;",
  "        state.explorerFilters.oaOnly = form.oaOnly.checked;",
  "        state.explorerFilters.bookmarkedOnly = form.bookmarkedOnly.checked;",
  "        await renderExplorer(project);",
  "      });",
  "",
  "      byId(\"addPaperForm\").addEventListener(\"submit\", async (event) => {",
  "        event.preventDefault();",
  "        const form = event.currentTarget;",
  "        const title = form.title.value.trim();",
  "        if (!title) {",
  "          showError(new Error(\"Title is required.\"));",
  "          return;",
  "        }",
  "        try {",
  "          await api(\"/api/projects/\" + project.id + \"/papers\", {",
  "            method: \"POST\",",
  "            body: JSON.stringify({",
  "              title,",
  "              doi: form.doi.value.trim() || undefined,",
  "              year: form.year.value ? Number(form.year.value) : undefined,",
  "              citationCount: form.citationCount.value ? Number(form.citationCount.value) : undefined,",
  "              abstract: form.abstract.value.trim() || undefined,",
  "              fieldsOfStudy: decodeListInput(form.fields.value)",
  "            })",
  "          });",
  "          await loadProjects();",
  "        } catch (error) {",
  "          showError(error);",
  "        }",
  "      });",
  "",
  "      content.querySelectorAll(\"button[data-action]\").forEach((button) => {",
  "        button.addEventListener(\"click\", async (event) => {",
  "          const action = event.currentTarget.getAttribute(\"data-action\");",
  "          const paperId = event.currentTarget.getAttribute(\"data-paper-id\");",
  "          if (!paperId) {",
  "            return;",
  "          }",
  "          try {",
  "            if (action === \"toggle-bookmark\") {",
  "              const current = event.currentTarget.getAttribute(\"data-current\") === \"1\";",
  "              await api(\"/api/projects/\" + project.id + \"/papers/\" + paperId, {",
  "                method: \"PATCH\",",
  "                body: JSON.stringify({ bookmarked: !current })",
  "              });",
  "              await loadProjects();",
  "              return;",
  "            }",
  "            if (action === \"toggle-reading\") {",
  "              const current = event.currentTarget.getAttribute(\"data-current\") === \"1\";",
  "              await api(\"/api/projects/\" + project.id + \"/papers/\" + paperId, {",
  "                method: \"PATCH\",",
  "                body: JSON.stringify({ inReadingList: !current })",
  "              });",
  "              await loadProjects();",
  "              return;",
  "            }",
  "            if (action === \"delete-paper\") {",
  "              if (!confirm(\"Remove this paper from the project?\")) {",
  "                return;",
  "              }",
  "              await api(\"/api/projects/\" + project.id + \"/papers/\" + paperId, {",
  "                method: \"DELETE\"",
  "              });",
  "              await loadProjects();",
  "              return;",
  "            }",
  "            if (action === \"toggle-comments\") {",
  "              if (state.openComments.has(paperId)) {",
  "                state.openComments.delete(paperId);",
  "                await renderExplorer(project);",
  "                return;",
  "              }",
  "              state.openComments.add(paperId);",
  "              if (!state.commentsByPaper.has(paperId)) {",
  "                const commentsPayload = await api(\"/api/projects/\" + project.id + \"/papers/\" + paperId + \"/comments\");",
  "                state.commentsByPaper.set(paperId, commentsPayload.comments || []);",
  "              }",
  "              await renderExplorer(project);",
  "            }",
  "          } catch (error) {",
  "            showError(error);",
  "          }",
  "        });",
  "      });",
  "",
  "      content.querySelectorAll(\".comment-form\").forEach((form) => {",
  "        form.addEventListener(\"submit\", async (event) => {",
  "          event.preventDefault();",
  "          const formNode = event.currentTarget;",
  "          const paperId = formNode.getAttribute(\"data-paper-id\");",
  "          const body = formNode.querySelector('textarea[name=\"body\"]').value.trim();",
  "          if (!paperId || !body) {",
  "            return;",
  "          }",
  "          try {",
  "            await api(\"/api/projects/\" + project.id + \"/papers/\" + paperId + \"/comments\", {",
  "              method: \"POST\",",
  "              body: JSON.stringify({ body })",
  "            });",
  "            const commentsPayload = await api(\"/api/projects/\" + project.id + \"/papers/\" + paperId + \"/comments\");",
  "            state.commentsByPaper.set(paperId, commentsPayload.comments || []);",
  "            await renderExplorer(project);",
  "          } catch (error) {",
  "            showError(error);",
  "          }",
  "        });",
  "      });",
  "    }",
  ""
].join("\n");
