export const navigationScript = [
  "    async function selectProject(projectId) {",
  "      state.activeProjectId = projectId;",
  "      if (state.activeView === \"new-project\") {",
  "        state.activeView = \"dashboard\";",
  "      }",
  "      await ensureChats(projectId, false);",
  "      renderSidebar();",
  "      await renderMain();",
  "    }",
  "",
  "    async function selectView(view, chatId) {",
  "      state.activeView = view;",
  "      state.activeChatId = chatId || null;",
  "      renderSidebar();",
  "      await renderMain();",
  "    }",
  "",
  "    async function createChat(projectId) {",
  "      const titleInput = prompt(\"Chat title (optional)\");",
  "      const title = typeof titleInput === \"string\" ? titleInput.trim() : \"\";",
  "      const payload = await api(\"/api/projects/\" + projectId + \"/chats\", {",
  "        method: \"POST\",",
  "        body: JSON.stringify({ title: title || undefined })",
  "      });",
  "      await ensureChats(projectId, true);",
  "      state.activeView = \"chat\";",
  "      state.activeChatId = payload.chat.id;",
  "      renderSidebar();",
  "      await renderMain();",
  "    }",
  "",
  "    function getActiveProject() {",
  "      return state.projects.find((project) => project.id === state.activeProjectId) || null;",
  "    }",
  "",
  "    function renderSidebar() {",
  "      const tree = byId(\"projectTree\");",
  "      clearNode(tree);",
  "",
  "      if (state.projects.length === 0) {",
  "        const empty = document.createElement(\"p\");",
  "        empty.className = \"empty-note\";",
  "        empty.textContent = \"No projects yet. Create one to start your thesis workspace.\";",
  "        tree.append(empty);",
  "        return;",
  "      }",
  "",
  "      state.projects.forEach((project) => {",
  "        const node = document.createElement(\"article\");",
  "        node.className = \"project-node\" + (project.id === state.activeProjectId ? \" active\" : \"\");",
  "",
  "        const trigger = document.createElement(\"button\");",
  "        trigger.type = \"button\";",
  "        trigger.className = \"project-trigger\";",
  "        trigger.addEventListener(\"click\", async () => {",
  "          try {",
  "            await selectProject(project.id);",
  "          } catch (error) {",
  "            showError(error);",
  "          }",
  "        });",
  "",
  "        const title = document.createElement(\"div\");",
  "        title.className = \"project-title\";",
  "        title.textContent = projectTitle(project);",
  "        trigger.append(title);",
  "",
  "        const meta = document.createElement(\"div\");",
  "        meta.className = \"project-meta\";",
  "        const status = document.createElement(\"span\");",
  "        status.textContent = projectStatusLabel(project);",
  "        meta.append(status);",
  "",
  "        const dot = document.createElement(\"span\");",
  "        dot.className = \"dot\";",
  "        meta.append(dot);",
  "",
  "        const count = document.createElement(\"span\");",
  "        count.textContent = String(project.counts.papers || 0) + \" papers\";",
  "        meta.append(count);",
  "",
  "        if (project.latestRun && project.latestRun.updatedAt) {",
  "          const dot2 = document.createElement(\"span\");",
  "          dot2.className = \"dot\";",
  "          meta.append(dot2);",
  "          const updated = document.createElement(\"span\");",
  "          updated.textContent = formatDate(project.latestRun.updatedAt);",
  "          meta.append(updated);",
  "        }",
  "",
  "        trigger.append(meta);",
  "        node.append(trigger);",
  "",
  "        if (project.id === state.activeProjectId) {",
  "          const children = document.createElement(\"div\");",
  "          children.className = \"project-children\";",
  "",
  "          const navItems = [",
  "            { key: \"dashboard\", label: \"Dashboard\" },",
  "            { key: \"explorer\", label: \"Paper Explorer\" },",
  "            { key: \"reading\", label: \"Reading List\" }",
  "          ];",
  "",
  "          navItems.forEach((entry) => {",
  "            const btn = document.createElement(\"button\");",
  "            btn.type = \"button\";",
  "            btn.className = \"subnav-btn\" + (state.activeView === entry.key ? \" active\" : \"\");",
  "            btn.textContent = entry.label;",
  "            btn.addEventListener(\"click\", async () => {",
  "              try {",
  "                await selectView(entry.key);",
  "              } catch (error) {",
  "                showError(error);",
  "              }",
  "            });",
  "            children.append(btn);",
  "          });",
  "",
  "          const chats = state.chatsByProject.get(project.id) || [];",
  "          const chatList = document.createElement(\"div\");",
  "          chatList.className = \"chat-list\";",
  "          if (chats.length === 0) {",
  "            const empty = document.createElement(\"div\");",
  "            empty.className = \"chat-empty\";",
  "            empty.textContent = \"No chats yet.\";",
  "            chatList.append(empty);",
  "          } else {",
  "            chats.forEach((chat) => {",
  "              const chatButton = document.createElement(\"button\");",
  "              chatButton.type = \"button\";",
  "              chatButton.className = \"chat-btn\" + (state.activeView === \"chat\" && state.activeChatId === chat.id ? \" active\" : \"\");",
  "              chatButton.textContent = chat.title;",
  "              chatButton.addEventListener(\"click\", async () => {",
  "                try {",
  "                  state.activeChatId = chat.id;",
  "                  await selectView(\"chat\", chat.id);",
  "                } catch (error) {",
  "                  showError(error);",
  "                }",
  "              });",
  "              chatList.append(chatButton);",
  "            });",
  "          }",
  "          children.append(chatList);",
  "",
  "          const addChatBtn = document.createElement(\"button\");",
  "          addChatBtn.type = \"button\";",
  "          addChatBtn.className = \"button soft\";",
  "          addChatBtn.textContent = \"+ New chat\";",
  "          addChatBtn.addEventListener(\"click\", async () => {",
  "            try {",
  "              await createChat(project.id);",
  "            } catch (error) {",
  "              showError(error);",
  "            }",
  "          });",
  "          children.append(addChatBtn);",
  "",
  "          node.append(children);",
  "        }",
  "",
  "        tree.append(node);",
  "      });",
  "    }",
  "",
  "    async function renderMain() {",
  "      const project = getActiveProject();",
  "",
  "      if (!project || state.activeView === \"new-project\") {",
  "        renderCreateProject();",
  "        return;",
  "      }",
  "",
  "      if (state.activeView === \"dashboard\") {",
  "        await renderDashboard(project);",
  "        return;",
  "      }",
  "      if (state.activeView === \"explorer\") {",
  "        await renderExplorer(project);",
  "        return;",
  "      }",
  "      if (state.activeView === \"reading\") {",
  "        await renderReadingList(project);",
  "        return;",
  "      }",
  "      if (state.activeView === \"chat\") {",
  "        await renderChat(project);",
  "        return;",
  "      }",
  "",
  "      renderCreateProject();",
  "    }",
  "",
  "    function renderCreateProject() {",
  "      setHeader(\"Create a Project\", \"Every new project starts with your thesis text and triggers background research.\", []);",
  "      const content = byId(\"mainContent\");",
  "      content.innerHTML =",
  "        '<article class=\"panel\">' +",
  "          '<h3>New project</h3>' +",
  "          '<p>Paste your thesis text to initialize your workspace, paper explorer, and chats.</p>' +",
  "          '<form id=\"createProjectForm\" class=\"stack\">' +",
  "            '<div class=\"field\"><label>Project title (optional)</label><input id=\"projectTitleInput\" type=\"text\" placeholder=\"e.g. AI and urban policy\" /></div>' +",
  "            '<div class=\"field\"><label>Thesis text</label><textarea id=\"projectThesisInput\" required minlength=\"30\" placeholder=\"Paste at least 30 characters\"></textarea></div>' +",
  "            '<div class=\"actions-row\"><button class=\"button accent\" type=\"submit\">Create project</button></div>' +",
  "          '</form>' +",
  "        '</article>';",
  "",
  "      const form = byId(\"createProjectForm\");",
  "      form.addEventListener(\"submit\", async (event) => {",
  "        event.preventDefault();",
  "        const title = byId(\"projectTitleInput\").value.trim();",
  "        const thesisText = byId(\"projectThesisInput\").value.trim();",
  "        if (thesisText.length < 30) {",
  "          showError(new Error(\"Please provide at least 30 characters of thesis text.\"));",
  "          return;",
  "        }",
  "        try {",
  "          await api(\"/api/projects\", {",
  "            method: \"POST\",",
  "            body: JSON.stringify({",
  "              title: title || undefined,",
  "              thesisText",
  "            })",
  "          });",
  "          state.activeView = \"dashboard\";",
  "          await loadProjects();",
  "        } catch (error) {",
  "          showError(error);",
  "        }",
  "      });",
  "    }",
  "",
  "    async function renderDashboard(project) {",
  "      const actions = [",
  "        makeButton(\"Refresh suggestions\", \"soft\", async () => {",
  "          try {",
  "            await api(\"/api/projects/\" + project.id + \"/runs\", { method: \"POST\" });",
  "            await loadProjects();",
  "          } catch (error) {",
  "            showError(error);",
  "          }",
  "        }),",
  "        makeButton(\"New chat\", \"accent\", async () => {",
  "          try {",
  "            await createChat(project.id);",
  "          } catch (error) {",
  "            showError(error);",
  "          }",
  "        })",
  "      ];",
  "      setHeader(projectTitle(project), \"Dashboard\", actions);",
  "",
  "      const [dashboardPayload, memoryPayload] = await Promise.all([",
  "        api(\"/api/projects/\" + project.id + \"/dashboard\"),",
  "        api(\"/api/projects/\" + project.id + \"/memory-docs\")",
  "      ]);",
  "      const dashboard = dashboardPayload.dashboard;",
  "      const memoryDocs = memoryPayload.memoryDocs || [];",
  "",
  "      const stats = dashboard.stats || {};",
  "      const latestRunLine = dashboard.latestRun",
  "        ? (dashboard.latestRun.status === \"FAILED\"",
  "          ? \"Background suggestions need another pass.\"",
  "          : (dashboard.latestRun.status === \"RUNNING\" || dashboard.latestRun.status === \"QUEUED\")",
  "            ? \"Background suggestions are updating.\"",
  "            : \"Background suggestions are ready.\")",
  "        : \"Suggestions will appear after the first background pass.\";",
  "",
  "      const content = byId(\"mainContent\");",
  "      content.innerHTML =",
  "        '<section class=\"grid four\">' +",
  "          '<article class=\"stat\"><div class=\"label\">Papers</div><div class=\"value\">' + escapeHtml(stats.papers || 0) + '</div></article>' +",
  "          '<article class=\"stat\"><div class=\"label\">Open Access</div><div class=\"value\">' + escapeHtml(stats.openAccess || 0) + '</div></article>' +",
  "          '<article class=\"stat\"><div class=\"label\">Reading List</div><div class=\"value\">' + escapeHtml(stats.readingList || 0) + '</div></article>' +",
  "          '<article class=\"stat\"><div class=\"label\">Chats</div><div class=\"value\">' + escapeHtml(stats.chats || 0) + '</div></article>' +",
  "        '</section>' +",
  "        '<article class=\"panel\">' +",
  "          '<h3>Project summary</h3>' +",
  "          '<p>' + escapeHtml(dashboard.summary && dashboard.summary.thesisSummary ? dashboard.summary.thesisSummary : \"Your thesis summary will appear after the background run completes.\") + '</p>' +",
  "          '<div class=\"chips\">' +",
  "            '<span class=\"chip\">Foundational: ' + escapeHtml(stats.foundational || 0) + '</span>' +",
  "            '<span class=\"chip\">Depth: ' + escapeHtml(stats.depth || 0) + '</span>' +",
  "            '<span class=\"chip\">Background: ' + escapeHtml(stats.background || 0) + '</span>' +",
  "            '<span class=\"chip\">Bookmarked: ' + escapeHtml(stats.bookmarked || 0) + '</span>' +",
  "          '</div>' +",
  "          '<p class=\"text-small\">' + escapeHtml(latestRunLine) + '</p>' +",
  "        '</article>' +",
  "        '<article class=\"panel\">' +",
  "          '<h3>Project memory docs</h3>' +",
  "          '<p>Chats automatically update memory. You can refine any document here.</p>' +",
  "          (memoryDocs.length === 0",
  "            ? '<p class=\"empty-note\">No memory docs yet.</p>'",
  "            : memoryDocs.map((doc) =>",
  "              '<form class=\"memory-form panel\" data-doc-key=\"' + escapeHtml(doc.key) + '\">' +",
  "                '<div class=\"grid two\">' +",
  "                  '<div class=\"field\"><label>Title</label><input name=\"title\" value=\"' + escapeHtml(doc.title) + '\" /></div>' +",
  "                  '<div class=\"field\"><label>Source</label><input value=\"' + escapeHtml(doc.source) + '\" disabled /></div>' +",
  "                '</div>' +",
  "                '<div class=\"field\"><label>Content</label><textarea name=\"content\">' + escapeHtml(doc.content) + '</textarea></div>' +",
  "                '<div class=\"actions-row\"><button type=\"submit\" class=\"button soft\">Save memory doc</button><span class=\"text-small\">Updated ' + escapeHtml(formatDate(doc.updatedAt)) + '</span></div>' +",
  "              '</form>'",
  "            ).join(\"\")) +",
  "        '</article>';",
  "",
  "      content.querySelectorAll(\".memory-form\").forEach((form) => {",
  "        form.addEventListener(\"submit\", async (event) => {",
  "          event.preventDefault();",
  "          const formNode = event.currentTarget;",
  "          const docKey = formNode.getAttribute(\"data-doc-key\");",
  "          const title = formNode.querySelector('input[name=\"title\"]').value.trim();",
  "          const body = formNode.querySelector('textarea[name=\"content\"]').value.trim();",
  "          if (!body) {",
  "            showError(new Error(\"Memory content cannot be empty.\"));",
  "            return;",
  "          }",
  "          try {",
  "            await api(\"/api/projects/\" + project.id + \"/memory-docs/\" + encodeURIComponent(docKey), {",
  "              method: \"PATCH\",",
  "              body: JSON.stringify({ title, content: body })",
  "            });",
  "            await renderDashboard(project);",
  "          } catch (error) {",
  "            showError(error);",
  "          }",
  "        });",
  "      });",
  "    }",
  "",
  "    function mapSortLabel(sort) {",
  "      if (sort === \"recent\") return \"Recent\";",
  "      if (sort === \"citations\") return \"Citations\";",
  "      if (sort === \"newest\") return \"Recently added\";",
  "      return \"Most relevant\";",
  "    }",
  "",
  "    function decodeListInput(raw) {",
  "      return raw",
  "        .split(\",\")",
  "        .map((item) => item.trim())",
  "        .filter(Boolean)",
  "        .filter((item, index, arr) => arr.findIndex((other) => other.toLowerCase() === item.toLowerCase()) === index);",
  "    }",
  ""
].join("\n");
